# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 00:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('front', models.CharField(max_length=1000)),
                ('back', models.CharField(max_length=1000)),
                ('review_time', models.DateTimeField(default=datetime.datetime)),
                ('card_audio', models.CharField(default='', max_length=300)),
                ('card_pic', models.CharField(default='', max_length=300)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
