# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_bobtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bobtest',
        ),
        migrations.AlterField(
            model_name='card',
            name='review_time',
            field=models.CharField(max_length=100),
        ),
    ]
