# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20160908_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='review_interval',
            field=models.BigIntegerField(default=60),
        ),
    ]
