# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_review_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
