# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_pic',
            field=models.FileField(default='', max_length=300, upload_to=''),
        ),
    ]
