# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20160908_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_score',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
