# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20160908_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Lyrics & Tabs'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_audio',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Youtube Link'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_pic',
            field=models.FileField(blank=True, upload_to='', verbose_name='Cover Picture'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_score',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Lyrics Link'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='Song Title'),
        ),
    ]
