# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 1, 16, 33, 63697)),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Is Favorite'),
        ),
    ]
