# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20160911_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_rating',
        ),
        migrations.AddField(
            model_name='card',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Is Pinned'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 1, 34, 28, 286342)),
        ),
    ]
