# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20160911_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[('U', 'public'), ('S', 'sharable'), ('P', 'private')], default=2, verbose_name='Card Privacy Setting'),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(blank=True, default='auto_generate', max_length=10000, verbose_name='Lyrics & Tabs'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_audio',
            field=models.CharField(blank=True, default='auto_generate', max_length=300, verbose_name='Youtube Link'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_pic',
            field=models.FileField(blank=True, upload_to='', verbose_name='Cover Picture (auto-generates if empty)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_score',
            field=models.CharField(blank=True, default='auto_generate', max_length=300, verbose_name='Lyrics Link'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 14, 12, 6, 3, 617529)),
        ),
        migrations.AlterField(
            model_name='card',
            name='review_interval',
            field=models.BigIntegerField(default=43200),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('topic', 'front')]),
        ),
    ]
