# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20160914_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bpm',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='beats per minute'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 14, 31, 50, 181265)),
        ),
    ]
