# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_auto_20160917_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 14, 32, 7, 376084)),
        ),
    ]
